#!/usr/bin/env bash
set -euo pipefail

RUNTIME_ROOT="${PX4_SITL_RUNTIME_ROOT:-/opt/ros/noetic/share/px4_sitl_1_14/runtime}"
WORK_DIR="${PX4_SITL_WORK_DIR:-/tmp/px4_sitl/uav1}"
INSTANCE="0"
STARTUP_SCRIPT="etc/init.d-posix/rcS"
PARAM_FILE="${PX4_SITL_PARAM_FILE:-}"
PARAM_BSON="${PX4_SITL_PARAM_BSON:-}"
RESET_PARAMS="${PX4_SITL_RESET_PARAMS:-false}"
EXTRA_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --runtime-root)
      RUNTIME_ROOT="$2"
      shift 2
      ;;
    --work-dir)
      WORK_DIR="$2"
      shift 2
      ;;
    --instance)
      INSTANCE="$2"
      shift 2
      ;;
    --script)
      STARTUP_SCRIPT="$2"
      shift 2
      ;;
    --param-file)
      PARAM_FILE="$2"
      shift 2
      ;;
    --param-bson)
      PARAM_BSON="$2"
      shift 2
      ;;
    --reset-params)
      RESET_PARAMS="true"
      shift
      ;;
    --)
      shift
      EXTRA_ARGS+=("$@")
      break
      ;;
    *)
      EXTRA_ARGS+=("$1")
      shift
      ;;
  esac
done

PX4_BIN="${RUNTIME_ROOT}/bin/px4"
PX4_ETC="${RUNTIME_ROOT}/etc"

if [[ ! -x "${PX4_BIN}" ]]; then
  echo "PX4 binary is missing or not executable: ${PX4_BIN}" >&2
  exit 1
fi

if [[ "${STARTUP_SCRIPT}" == /* ]]; then
  STARTUP_SCRIPT_PATH="${STARTUP_SCRIPT}"
  STARTUP_SCRIPT_ARG="${STARTUP_SCRIPT}"
elif [[ "${STARTUP_SCRIPT}" == etc/* ]]; then
  STARTUP_SCRIPT_PATH="${RUNTIME_ROOT}/${STARTUP_SCRIPT}"
  STARTUP_SCRIPT_ARG="${STARTUP_SCRIPT}"
else
  STARTUP_SCRIPT_PATH="${PX4_ETC}/${STARTUP_SCRIPT}"
  STARTUP_SCRIPT_ARG="${STARTUP_SCRIPT}"
fi

if [[ ! -f "${STARTUP_SCRIPT_PATH}" ]]; then
  echo "PX4 startup script is missing: ${STARTUP_SCRIPT_PATH}" >&2
  exit 1
fi

if [[ -n "${PARAM_FILE}" && "${PARAM_FILE}" != /* ]]; then
  PARAM_FILE="$(realpath "${PARAM_FILE}")"
fi

if [[ -n "${PARAM_BSON}" && "${PARAM_BSON}" != /* ]]; then
  PARAM_BSON="$(realpath "${PARAM_BSON}")"
fi

mkdir -p "${WORK_DIR}"
cd "${WORK_DIR}"

if [[ "${RESET_PARAMS}" == "true" ]]; then
  rm -f parameters.bson parameters_backup.bson param_import_fail.bson px4-rc.params
fi

if [[ -n "${PARAM_BSON}" ]]; then
  if [[ ! -f "${PARAM_BSON}" ]]; then
    echo "PX4 BSON parameter file does not exist: ${PARAM_BSON}" >&2
    exit 1
  fi
  install -m 0644 "${PARAM_BSON}" parameters.bson
fi

if [[ -n "${PARAM_FILE}" ]]; then
  if [[ ! -f "${PARAM_FILE}" ]]; then
    echo "PX4 text parameter file does not exist: ${PARAM_FILE}" >&2
    exit 1
  fi
  {
    echo "# Generated by run_px4_sitl.sh from ${PARAM_FILE}"
    awk '
      /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
      NF >= 4 { printf "param set %s %s\n", $3, $4 }
    ' "${PARAM_FILE}"
  } > px4-rc.params
fi

export PATH="${WORK_DIR}:${RUNTIME_ROOT}/bin:${PATH}"

exec "${PX4_BIN}" "${PX4_ETC}" -s "${STARTUP_SCRIPT_ARG}" -i "${INSTANCE}" "${EXTRA_ARGS[@]}"
