#!/usr/bin/env bash
set -euo pipefail

RUNTIME_ROOT="${PX4_SITL_RUNTIME_ROOT:-/opt/ros/noetic/share/px4_sitl_runtime_1_14/runtime}"
GAZEBO_RUNTIME_ROOT="${SITL_GAZEBO_CLASSIC_ROOT:-/opt/ros/noetic/share/sitl_gazebo_1_14}"
GAZEBO_PLUGIN_ROOT="${SITL_GAZEBO_CLASSIC_PLUGIN_ROOT:-/opt/ros/noetic/lib/sitl_gazebo_1_14}"

export PX4_SITL_RUNTIME_ROOT="${RUNTIME_ROOT}"
export SITL_GAZEBO_CLASSIC_ROOT="${GAZEBO_RUNTIME_ROOT}"
export SITL_GAZEBO_CLASSIC_PLUGIN_ROOT="${GAZEBO_PLUGIN_ROOT}"
export GAZEBO_PLUGIN_PATH="${GAZEBO_PLUGIN_ROOT}:${GAZEBO_PLUGIN_PATH:-}"
export GAZEBO_MODEL_PATH="${GAZEBO_RUNTIME_ROOT}/models:${GAZEBO_MODEL_PATH:-}"
export LD_LIBRARY_PATH="${GAZEBO_PLUGIN_ROOT}:${LD_LIBRARY_PATH:-}"

echo "PX4_SITL_RUNTIME_ROOT=${PX4_SITL_RUNTIME_ROOT}"
echo "SITL_GAZEBO_CLASSIC_ROOT=${SITL_GAZEBO_CLASSIC_ROOT}"
echo "SITL_GAZEBO_CLASSIC_PLUGIN_ROOT=${SITL_GAZEBO_CLASSIC_PLUGIN_ROOT}"
