#!/usr/bin/env bash
set -euo pipefail

RUNTIME_ROOT="${PX4_SITL_RUNTIME_ROOT:-/opt/xgc/px4_sitl_runtime/1.16.2}"
GAZEBO_RUNTIME_ROOT="${SITL_GAZEBO_CLASSIC_ROOT:-/opt/xgc/px4_gz_sim/1.16.2}"

export PX4_SITL_RUNTIME_ROOT="${RUNTIME_ROOT}"
export SITL_GAZEBO_CLASSIC_ROOT="${GAZEBO_RUNTIME_ROOT}"
export GAZEBO_PLUGIN_PATH="${GAZEBO_RUNTIME_ROOT}/lib:${GAZEBO_PLUGIN_PATH:-}"
export GAZEBO_MODEL_PATH="${GAZEBO_RUNTIME_ROOT}/models:${GAZEBO_MODEL_PATH:-}"
export LD_LIBRARY_PATH="${GAZEBO_RUNTIME_ROOT}/lib:${LD_LIBRARY_PATH:-}"

echo "PX4_SITL_RUNTIME_ROOT=${PX4_SITL_RUNTIME_ROOT}"
echo "SITL_GAZEBO_CLASSIC_ROOT=${SITL_GAZEBO_CLASSIC_ROOT}"
